[theme]
base = "light"
primaryColor = "#0070f3"              
backgroundColor = "#ffffff"            
secondaryBackgroundColor = "#fafafa"   
textColor = "#333333"                  
font = "sans serif"

[browser]
gatherUsageStats = false
